name: Notify Slack on Issue Activity

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github) }}"
      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *${{ github.event_name }}: ${{ github.event.issue.title }}* in <{repo_url}|{repo}>"
          footer: "URL: <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
