name: Notify Slack on Issue Activity

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack Action
        uses: ravsamhq/notify-slack-action@2.5.0
        with:
          status: ${{ github.event.action }}
          notification_title: "GitHub Issue Notification"
          message: Issue #${{ github.event.issue.number }} ${{ github.event.action }} by ${{ github.event.sender.login }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
